columnSuffix: null
handle: boxiesIntro
instructions: 'Short description shown under the Boxies heading.'
name: 'Boxies Intro'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
