columnSuffix: null
handle: scottQuote
instructions: 'Quote shown when hovering this box art.'
name: 'Scott Quote'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
